# Generated by Django 4.2.3 on 2023-08-02 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('CE', 'Cardiovascular Exercise'), ('ST', 'Strength Training'), ('FS', 'Flexibility and Stretching'), ('BS', 'Balance and Stability'), ('CC', 'Core Conditioning'), ('ET', 'Endurance Training'), ('BT', 'Bodyweight Training'), ('RM', 'Relaxation and Mindfulness')], max_length=100, unique=True)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
