# Generated by Django 4.2.3 on 2023-08-04 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_fitnesscategory_goal_activities_goal_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='activities',
            field=models.CharField(max_length=200),
        ),
    ]
