# Generated by Django 4.2.3 on 2023-08-02 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_fitnesscategory_goal_end_date_goal_start_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('fitness_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.fitnesscategory')),
            ],
        ),
    ]
