# Generated by Django 4.2.3 on 2023-08-04 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_fitnesscategory_goal_activities_goal_end_date_and_more'),
        ('main_app', '0002_userprofile'),
    ]

    operations = [
    ]
