# Generated by Django 4.2.3 on 2023-08-04 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_merge_20230804_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='activities',
            field=models.CharField(max_length=200),
        ),
    ]
