# Generated by Django 4.2.3 on 2023-08-02 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitnesscategory',
            name='name',
            field=models.CharField(choices=[('CE', 'Cardiovascular Exercise'), ('ST', 'Strength Training'), ('FS', 'Flexibility and Stretching'), ('BS', 'Balance and Stability'), ('CC', 'Core Conditioning'), ('ET', 'Endurance Training'), ('BT', 'Bodyweight Training'), ('RM', 'Relaxation and Mindfulness')], default='CE', max_length=2),
        ),
    ]
