# Generated by Django 4.2.3 on 2023-08-04 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_goal_activities'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoalPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='goal_photos/')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.goal')),
            ],
        ),
    ]
