# Generated by Django 4.2.3 on 2023-08-02 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_fitnesscategory_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='fitness_category',
        ),
        migrations.AddField(
            model_name='goal',
            name='activities',
            field=models.ManyToManyField(to='main_app.activity'),
        ),
        migrations.AlterField(
            model_name='fitnesscategory',
            name='name',
            field=models.CharField(choices=[('CE', 'Cardiovascular Exercise'), ('ST', 'Strength Training'), ('FS', 'Flexibility and Stretching'), ('BS', 'Balance and Stability'), ('CC', 'Core Conditioning'), ('ET', 'Endurance Training'), ('BT', 'Bodyweight Training'), ('RM', 'Relaxation and Mindfulness')], max_length=100),
        ),
    ]
