# Generated by Django 4.2.3 on 2023-08-07 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_userprofile'),
        ('main_app', '0005_alter_profile_gender_historicaldata'),
    ]

    operations = [
    ]
