# Generated by Django 4.2.3 on 2023-08-07 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_merge_20230807_0222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='HistoricalData',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
