# Generated by Django 4.2.3 on 2023-08-02 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_fitnesscategory_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='activities',
            field=models.ManyToManyField(to='main_app.activity'),
        ),
    ]
