# Generated by Django 4.2.3 on 2023-08-03 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_goal_activities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='description',
        ),
    ]
