# Generated by Django 4.2.3 on 2023-08-03 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_remove_activity_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='activities',
        ),
        migrations.AddField(
            model_name='goal',
            name='activities',
            field=models.CharField(default='default_value', max_length=200),
        ),
    ]
