# Generated by Django 4.2.3 on 2023-08-03 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_remove_goal_activities_goal_activities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitnesscategory',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
